### ISSUE TITLE
No module named builtins

### ISSUE THREAD

**Issue by taur** [boileaum/gitlab-users#2]
On Ubuntu 18.04 i get the following error:
```
# gitlab-users
Traceback (most recent call last):
  File "/usr/local/bin/gitlab-users", line 7, in <module>
    from gitlab_users.gitlab_users import main
  File "/usr/local/lib/python2.7/dist-packages/gitlab_users/gitlab_users.py", line 10, in <module>
    from builtins import super, str, input
ImportError: No module named builtins
```

**Comment by boileaum** [comment]
Thanks for reporting. This is actually solved in release `0.8.2`.
